blank_issues_enabled: true
contact_links:
  - name: Problema no texto original em inglês
    url: https://github.com/progit/progit2/issues
    about: Relate no repositório inglês os problemas que também existem na fonte original.

  - name: Problema no site git-scm.com
    url: https://github.com/git/git-scm.com/issues/
    about: Relate nesse repositório os problemas específicos do site.

  - name: Problema no programa Git
    url: https://git-scm.com/community
    about: Consulte os canais da comunidade para relatar problemas do próprio Git.

  - name: Problema no Git for Windows
    url: https://github.com/git-for-windows/git/issues
    about: Relate nesse repositório os problemas específicos do Git for Windows.
