name: Propor uma melhoria
description: Sugira uma melhoria para a tradução ou para o repositório pt-BR
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Visão geral da proposta
      description: Descreva objetivamente a mudança sugerida.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Que problema isso resolve?
      description: Explique por que a mudança seria útil para quem lê ou contribui.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternativas consideradas
      description: Informe outras soluções avaliadas, se houver.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Você gostaria de ajudar a implementar essa melhoria?
      options:
        - "Sim"
        - "Talvez"
        - "Não"
    validations:
      required: true
